spring:
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    url: jdbc:hsqldb:mem:twitter
    driver-class-name: org.hsqldb.jdbcDriver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: create-drop
    
com.vinicius.twitter:
  applicationName: Twitter
  info:
    projectName: @parent.name@
    version: @project.version@
    timestamp: @creation.time.timestamp@

management:
  security:
    enabled: false
  context-path: /actuator