spring:
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    url: jdbc:hsqldb:mem:twitter
    driver-class-name: org.hsqldb.jdbcDriver
    username: sa
    password: null
  jpa:
    hibernate:
      ddl-auto: create-drop
